# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'ios_project' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ios_project
  pod 'Alamofire', '~> 4.7'
  pod 'AlamofireImage', '~> 3.3'
  pod 'ReactiveSwift', '~> 3.0'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'
  pod 'SwiftyJSON'

  target 'ios_projectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ios_projectUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
